services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    # Переменные окружения для БД будут загружены из .env файлов
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    # Команда запуска остается прежней, entrypoint.sh будет выполняться всегда
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Переменные окружения для Django также будут из .env файлов
    environment:
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: db
      PGPORT: 5432
      # Ключ и режим DEBUG теперь управляются централизованно
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    depends_on:
      - db

volumes:
  postgres_data:
