# docker-compose.prod.yml - НАСТРОЙКИ ДЛЯ ПРОДАКШЕНА (prod)

services:
  web:
    # В продакшене порты могут быть другими или управляться через прокси (например, Nginx)
    # Оставляем 8000 как внутренний порт контейнера
    ports:
      - "80:8000" # Пример: маппинг на стандартный порт 80
    env_file:
      # Указываем, какой файл с переменными окружения использовать
      - ./.env.prod
