# docker-compose.override.yml - НАСТРОЙКИ ДЛЯ РАЗРАБОТКИ (dev)

services:
  db:
    ports:
      # Пробрасываем порт базы данных только в режиме разработки
      - "5432:5432"

  web:
    volumes:
      # Подключаем текущую директорию в контейнер для "живой" перезагрузки кода
      - .:/app
    ports:
      # Пробрасываем порт веб-приложения
      - "8000:8000"
    env_file:
      # Указываем, какой файл с переменными окружения использовать
      - ./.env.dev
    command:
      # В режиме разработки используем manage.py runserver для автоперезагрузки
      python manage.py runserver 0.0.0.0:8000
